# fly.toml app configuration file generated for tmap-web-be on 2026-05-12T22:57:36-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tmap-web-be'
primary_region = 'nrt'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '15s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
